// SPDX-License-Identifier: GPL-3.0-only

/**
 * Downloads the upstream filter lists and compiles them into DNR rulesets.
 *
 *   pnpm compile-lists            # uses .cache/lists/*.txt if < 24h old
 *   pnpm compile-lists --refresh  # always re-download
 *
 * Outputs (all git-ignored, regenerated by every `pnpm build`):
 *   rulesets/<id>.json   — the DNR rules, referenced from manifest.config.ts
 *   public/lists.json    — metadata (rule counts, skip stats, fetch time)
 *                          shown on the options page
 *
 * Run with: node --experimental-strip-types scripts/compile-lists.ts
 */
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { convertList } from "../src/compiler/abp-to-dnr.ts";
import { FILTER_LISTS } from "../src/shared/filter-lists.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const cacheDir = path.join(root, ".cache", "lists");
const CACHE_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const refresh = process.argv.includes("--refresh");

async function fetchList(id: string, url: string): Promise<{ text: string; fromCache: boolean }> {
  const cached = path.join(cacheDir, `${id}.txt`);
  if (!refresh) {
    try {
      const info = await stat(cached);
      if (Date.now() - info.mtimeMs < CACHE_MAX_AGE_MS) {
        return { text: await readFile(cached, "utf8"), fromCache: true };
      }
    } catch {
      // no cache yet
    }
  }
  const res = await fetch(url, { headers: { "user-agent": "Nullbanner list compiler" } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const text = await res.text();
  await mkdir(cacheDir, { recursive: true });
  await writeFile(cached, text);
  return { text, fromCache: false };
}

const meta = [];
for (const list of FILTER_LISTS) {
  const { text, fromCache } = await fetchList(list.id, list.url);
  const { rules, stats } = convertList(text);
  const outPath = path.join(root, "rulesets", `${list.id}.json`);
  await writeFile(outPath, JSON.stringify(rules));
  const skipped = Object.entries(stats.skipped)
    .filter(([, n]) => n > 0)
    .map(([k, n]) => `${k}=${n}`)
    .join(" ");
  console.log(
    `${list.id}: ${stats.converted} rules from ${stats.sourceLines} lines` +
      ` (${fromCache ? "cache" : "downloaded"}; skipped ${skipped})`
  );
  meta.push({ ...list, ruleCount: stats.converted, sourceLines: stats.sourceLines, skipped: stats.skipped });
}

await mkdir(path.join(root, "public"), { recursive: true });
await writeFile(
  path.join(root, "public", "lists.json"),
  JSON.stringify({ generatedAt: new Date().toISOString(), lists: meta }, null, 2) + "\n"
);
